# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-16 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='address',
            field=models.CharField(default='\u5730\u5740', max_length=100, verbose_name='\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='courseorg',
            name='image',
            field=models.ImageField(upload_to='org/%Y/%m', verbose_name='\u5c01\u9762\u56fe'),
        ),
    ]
